package:
  name: numpy
  version: 1.11

source:
  fn: numpy-1.11.tar.gz
  url: https://pypi.python.org/packages/source/n/numpy/numpy-1.11.0.tar.gz
  md5: bc56fb9fc2895aa4961802ffbdb31d0b

requirements:
  build:
    - python
    - mkl_seq
  run:
    - python
    - mkl_seq

build:
  string: py{{py}}_mkl_seq
  features:
    - mkl_seq

test:
  requires:
    - nose
  imports:
    - numpy
    - numpy.linalg.lapack_lite

about:
  home: http://numpy.scipy.org/
  license: BSD
